### ISSUE TITLE
[xx-xxx-xxxxx xx:xx:xx Europe/Berlin] [critical] Mailmagik: ["Can not authenticate to IMAP server: [AUTHENTICATIONFAILED] Authentication failed."]

### ISSUE THREAD

**Issue by creecros** [creecros/Mailmagik#28]
From #25 by @JustFxDev

0.) Fatal Error
An incorrect imap e-mal password or something like that disables the plug in. It disappears from the list of installed plugins. This leads to this situation: I cannot correct the password in the application setting / e-mal setup. The fields are no longer there.

Even a new installation does not change this, because the wrong information is still in the database.

I fixed that by changing it directly in the database.

That occurred also as the server had certification problems (this was the reason why I found that initial out)

Error-log:
[xx-xxx-xxxxx xx:xx:xx Europe/Berlin] [critical] Mailmagik: ["Can not authenticate to IMAP server: [AUTHENTICATIONFAILED] Authentication failed."]

**Comment by creecros** [comment]
@alfredbuehler 
This is due to an infinite loop created by the Folders feature.

```
$this->template->hook->attach('template:config:email', 'mailmagik:config/config', array(
            'folders' => $this->helper->mailHelper->getFolders(),
        ));
```

The plugin dies here in Plugin.php and therefore will never load when it cannot authenticate.

**Comment by alfredbuehler** [comment]
Fixed by b63be9bfc5aab0d97cc51c1280ea35847b583ae6.

**Comment by creecros** [comment]
not quite. now it dies in the config when it hits the INBOX.

**Comment by alfredbuehler** [comment]
For testing, I have removed my password from the settings. So I'm unable to login and get the folder list. But I don't see any errors.

**Comment by creecros** [comment]
i dont errors either, i am guessing there is a `die()` somewhere in the vendor library. im currently clueless, and have been looking at it for an hour already.

**Comment by alfredbuehler** [comment]
But how did you get the screenshot above?

**Comment by creecros** [comment]
![Peek](https://user-images.githubusercontent.com/26339368/222744601-1f9c3126-4027-4ab8-b0cc-9bf3b16306c7.gif)

**Comment by alfredbuehler** [comment]
What says the Webservers log?

**Comment by creecros** [comment]
my nginx log is empty....

**Comment by alfredbuehler** [comment]
I tried to enforce with the wrong credentials, no way. Furthermore, not with another IMAP server. Everything works here.

**Comment by creecros** [comment]
whats your KB version and php? I'll try to match and see if its related to my version somehow

**Comment by JustFxDev** [comment]
I'am not deeply in that topic, but maybe it is possible to do a test upfront if a connection is possible and then if not force the user to remove the imap config / clear it or to correct it?

Only in case of a working connection the plugin goes on?

Just asking. Sorry if this is nonsense.

**Comment by JustFxDev** [comment]
Maybe this helps

![grafik](https://user-images.githubusercontent.com/82320201/222748991-31a64c2c-1ca6-4c9e-867b-788c37b3dbc4.png)

This is the environment where i can reproduce this isse

**Comment by creecros** [comment]
So you can reproduce it? Then its not a version thing.

Curious that alfred cannot reproduce.

**Comment by JustFxDev** [comment]
Moment! Not for actual changes!

I may test this if i get the code

**Comment by JustFxDev** [comment]
Just let me know if i can assist

**Comment by alfredbuehler** [comment]
I'm getting closer, so let me fix it.

**Comment by JustFxDev** [comment]
Do your thing! ;-)

**Comment by JustFxDev** [comment]
What about a discord place for such things?

**Comment by JustFxDev** [comment]
Silly question? How does that work?

I'am thinking about a chat chanel in general, but for such issues an other chanel is more than sufficent

**Comment by creecros** [comment]
you just make a channel and start inviting people. like this.

https://discord.gg/DWQYsqpy

**Comment by JustFxDev** [comment]
I know 😄 

But i'am unsure if this is something people like to use and i would preferre to allow "others" as well to use...

I can start such a chanel.... but how can i tell... i would like to have support to do so....

**Comment by creecros** [comment]
I am so confused by the question. maybe it is the language barrier.

the only way to know, is to try I guess. I would say, more people are likely to use discord since they are computer oriented people, who more than likely have played a video game in their life, than use something like slack, which is to far to the left for me.... :smile:

**Comment by JustFxDev** [comment]
I think you understood 😄 

Maybe i start a channel...

**Comment by JustFxDev** [comment]
Off for now.

I wish you a nice, relaxing weekend!

**Comment by alfredbuehler** [comment]
Meanwhile, I know the source, but not the solution. 

That crappy "new Mailbox" doesn't throw an InvalidParameterException nor does it return false, both as documented, when we pass bogus arguments to the call. How can we check the validity of a mailbox then? I'm still on it.

**Comment by creecros** [comment]
i pushed.

**Comment by creecros** [comment]
might make more sense to move that logic up into the login() function so that the function will return false, but basically we need to login, and then test the connection to determine a false.

**Comment by alfredbuehler** [comment]
> sounds good, i wont parallel you this time i swear!

Thank you for the fish! :(

**Comment by creecros** [comment]
> How can we check the validity of a mailbox then?

it sounded like you were asking me, and so i found the answer, figured you would notice the push. my bad.
