### ISSUE TITLE
Installed in Kanboard 1.2.27, no parsing options

### ISSUE THREAD

**Issue by pahles** [creecros/Mailmagik#30]
I just installed Kanboard 1.2.27 using Docker which looks to be functioning fine.
Tried to install Mailmagik 1.2.1. When configuring Kanboard crashes immediately complaining about Undefined constant 'OP_READONLY', even though I followed the instructions to install php-imap and php81-fileinfo in the container. After removing the plugin folder I was able to get back in Kanboard.
Then installed Mailmagik 1.2.0. I can configure it without a problem. Only thing that I see is that there is no pane to select the parsing options, neither with 1.2.0 nor 1.2.1...

Kanboard does not seem to fetch the emails I sent to a specifically created gmail address (which uses 2FA, and I did get an app password for Mailmagik).

How can I debug?

**Comment by creecros** [comment]
>Tried to install Mailmagik 1.2.1. When configuring Kanboard crashes immediately complaining about Undefined constant 'OP_READONLY', even though I followed the instructions to install php-imap and php81-fileinfo in the container. After removing the plugin folder I was able to get back in Kanboard.

The OP_READONLY message is exactly that, you were missing the reqs. so yes, you need php-imap and php81-fileinfo. However, you definitely need to restart the container after installing them.

>Only thing that I see is that there is no pane to select the parsing options, neither with 1.2.0 nor 1.2.1...

The parsing options are only available in 1.2.2, which I have not released as of yet, we are still working on it, as there are a few issues needed to be resolved.

>Kanboard does not seem to fetch the emails I sent to a specifically created gmail address (which uses 2FA, and I did get an app password for Mailmagik).

@alfredbuehler might be abe to help you with Gmail, I never have used gmail, as it annoys me. I used gmx in all my testing, and I recommend that, if its possible for you. Also, just a reminder, that the sender must be also match a user in the project or the email will be ignored.

**Comment by pahles** [comment]
> > Tried to install Mailmagik 1.2.1. When configuring Kanboard crashes immediately complaining about Undefined constant 'OP_READONLY', even though I followed the instructions to install php-imap and php81-fileinfo in the container. After removing the plugin folder I was able to get back in Kanboard.
> 
> The OP_READONLY message is exactly that, you were missing the reqs. so yes, you need php-imap and php81-fileinfo. However, you definitely need to restart the container after installing them.

I did install the reqs first AND restarted the container. 
> 
> > Only thing that I see is that there is no pane to select the parsing options, neither with 1.2.0 nor 1.2.1...
> 
> The parsing options are only available in 1.2.2, which I have not released as of yet, we are still working on it, as there are a few issues needed to be resolved.

Okay, this is not clear from the installation instructions...
> 
> > Kanboard does not seem to fetch the emails I sent to a specifically created gmail address (which uses 2FA, and I did get an app password for Mailmagik).
> 
> @alfredbuehler might be abe to help you with Gmail, I never have used gmail, as it annoys me. I used gmx in all my testing, and I recommend that, if its possible for you. Also, just a reminder, that the sender must be also match a user in the project or the email will be ignored.

The sender matches the user in the project.

**Comment by creecros** [comment]
>I did install the reqs first AND restarted the container.

Maybe 2 restarts, no idea, I just know, 100% fact, it is the message you will get if php-imap is not enabled. It sounds like you got it working anyway.

**Comment by pahles** [comment]
Well, no. Unfortunately the Readme is unclear. Apparently you are still working on the parsing of the subject thing, but this is nowhere stated, unless you read the issues/discussions. And even then it is not yet working like it should (according to https://github.com/creecros/Mailmagik/discussions/25). The Readme should state that this is not present in version 1.2.1...

Also, after installing 1.2.1 apparently something went wrong after I fill out the settings form (wrong password?). The settings form then disappears, and the plugin somehow is not installed anymore.

Also, it would be nice to show how to set up the specific action(s). Kanboard-newbies like me have no idea how to do that.

**Comment by creecros** [comment]
> Well, no. Unfortunately the Readme is unclear. Apparently you are still working on the parsing of the subject thing, but this is nowhere stated, unless you read the issues/discussions. And even then it is not yet working like it should (according to #25). The Readme should state that this is not present in version 1.2.1...

Apologies that this is not clear. This is an active project that has been in development for kind of a short period of time. We are actively updating and working out a few bugs. Have patience. The Main repo reflects version 1.2.2 which is still being developed, and the parsing option is new. Keep in mind, our time is unpaid, free, and our leisure. You are welcome. 

> Also, after installing 1.2.1 apparently something went wrong after I fill out the settings form (wrong password?). The settings form then disappears, and the plugin somehow is not installed anymore.

This is a known bug that has been fixed in v 1.2.2, which again, we are actively working on completing. Use an older version if you cannot wait, I would suggest 1.1.1, as that bug was introduced in 1.2.0. 

> Also, it would be nice to show how to set up the specific action(s). Kanboard-newbies like me have no idea how to do that.

https://docs.kanboard.org/v1/user/automatic_actions/

**Comment by creecros** [comment]
None of these issues, or complaints are unknown. Closing.

**Comment by creecros** [comment]
1.2.2 should now be bug free. So you are welcome to test and provide any new issue reports.

**Comment by pahles** [comment]
I'm sorry if I appeared irritated. I would really like this to work as this would be a very welcome addition to Kanboard, which I'm liking more and more. 

The reason I complained about the Readme is that I'm not used to this way of working. I'm used to development taking place in a development branch, not in the main branch. The main branch then always is the latest working release.

Going to try it as soon as possible.

**Comment by creecros** [comment]
No worries.

I am not traditional. I am a self taught hobbyist, with no formal training in anyway shape form or fashion. I am in the packaging industry, and simply do what I have figured out how to do. I make no claims of being an expert or pro at this. 

contributions are always welcome.
