### ISSUE TITLE
Emails not fetching

### ISSUE THREAD

**Issue by fernandodiacenco** [creecros/Mailmagik#33]
Hello, I'm using a brand new install o Kanboard 1.2.30, on Debian 12 running Apache, PostgreSQL and PHP 7.4

Kanboard its the only thing running on this server, and its installed at /var/www/html/kanboard

All modules appear to be installed correctly, as shown by php -m

```
[PHP Modules]
calendar Core ctype curl date dom exif FFI fileinfo filter ftp gd gettext hash iconv imap json ldap libxml mbstring openssl pcntl pcre PDO pdo_pgsql pgsql Phar posix readline Reflection session shmop SimpleXML sockets sodium SPL standard sysvmsg sysvsem sysvshm tokenizer xml xmlreader xmlwriter xsl Zend OPcache zip zlib

[Zend Modules]
Zend OPcache
```

Mailmagik plugin v1.2.2 installed without issues and is configured, the automatic actions are configured as well

When I run **/var/www/html/./cli mailmagik:fetchmail** it appears to run correctly and finishes without error, apache2 don't show any error

Yet, nothing happens, the emails are not marked as read or deleted depending on config, no tasks are created on the board

I tried with a Microsoft account and a brand new Gmail account with imap activated, and app password set, neither the standard account password or the app password worked

I suspect something happens when Mailmagik tries fetching the emails and fails, but I don't know where are the log files for that operation, where I can find the logs?

Thank you.

**Comment by creecros** [comment]
Does the Task email feature work?

**Comment by fernandodiacenco** [comment]
Does not seem to work, the automatic actions are set but nothing happens

![image](https://github.com/creecros/Mailmagik/assets/2643364/933768c4-ece0-4e20-be1e-acd729c94615)

![image](https://github.com/creecros/Mailmagik/assets/2643364/03719a8a-e6ba-4a2c-baae-7a2bfcb09f48)

The only task shown is one I created manually as a placeholder

![image](https://github.com/creecros/Mailmagik/assets/2643364/37f95e47-67f6-42c2-8ae7-d11c7a1611b9)

Emails sent as test as seen from gmail

![image](https://github.com/creecros/Mailmagik/assets/2643364/88e443ee-cc73-42ce-bb47-55f2ab6e6c3d)

**Comment by creecros** [comment]
Also, im not sure you parse option, but if you are parsing via subject line, your subject is incorrect

**Comment by creecros** [comment]
Must be as it is in the readme.

When using the TO: option, see examples below:

to send an email directly to a task: Task#1<myemail@email.com>
to send an email to a project for task conversion: Project#1<myemail@email.com>
to send an email to a task for comment conversion: CommentOnTask#1<myemail@email.com>
When using the SUBJECT: option, see examples below:

to send an email directly to a task: [Task#1]  should appear at the start of the Subject
to send an email to a project for task conversion: [Project#1]  should appear at the start of the Subject
to send an email to a task for comment conversion: [CommentOnTask#1]  should appear at the start of the Subject
note: the action must be in brackets

**Comment by creecros** [comment]
The brackets are a must as well, if using Subject as parse.

**Comment by alfredbuehler** [comment]
> Ah its working if you set up with the app password instead of the standard account password
